openapi: 3.1.0
info:
  title: Node Status API Status Gateways API
  description: ''
  contact:
    name: Nym Technologies SA
  license:
    name: Apache-2.0
    identifier: Apache-2.0
  version: 4.6.2
tags:
- name: Gateways
paths:
  /v2/gateways:
    get:
      tags:
      - Gateways
      operationId: gateways
      parameters:
      - name: size
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
      - name: page
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResult_Gateway'
  /v2/gateways/skinny:
    get:
      tags:
      - Gateways
      operationId: gateways_skinny
      parameters:
      - name: size
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
      - name: page
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResult_GatewaySkinny'
  /v2/gateways/{identity_key}:
    get:
      tags:
      - Gateways
      operationId: get_gateway
      parameters:
      - name: identity_key
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gateway'
components:
  schemas:
    PagedResult_GatewaySkinny:
      type: object
      required:
      - page
      - size
      - total
      - items
      properties:
        items:
          type: array
          items:
            type: object
            required:
            - gateway_identity_key
            - last_updated_utc
            - routing_score
            - config_score
            - performance
            properties:
              config_score:
                type: integer
                format: int32
                minimum: 0
              explorer_pretty_bond: {}
              gateway_identity_key:
                type: string
              last_ports_check_utc:
                type:
                - string
                - 'null'
              last_probe_result: {}
              last_testrun_utc:
                type:
                - string
                - 'null'
              last_updated_utc:
                type: string
              performance:
                type: integer
                format: int32
                minimum: 0
              ports_check: {}
              routing_score:
                type: number
                format: float
              self_described: {}
        page:
          type: integer
          minimum: 0
        size:
          type: integer
          minimum: 0
        total:
          type: integer
          minimum: 0
    Gateway:
      type: object
      required:
      - gateway_identity_key
      - bonded
      - performance
      - description
      - last_updated_utc
      - routing_score
      - config_score
      properties:
        bonded:
          type: boolean
        bridges: {}
        config_score:
          type: integer
          format: int32
          minimum: 0
        description:
          $ref: '#/components/schemas/NodeDescription'
        explorer_pretty_bond: {}
        gateway_identity_key:
          type: string
        last_ports_check_utc:
          type:
          - string
          - 'null'
        last_probe_log:
          type:
          - string
          - 'null'
        last_probe_result: {}
        last_testrun_utc:
          type:
          - string
          - 'null'
        last_updated_utc:
          type: string
        performance:
          type: integer
          format: int32
          minimum: 0
        ports_check: {}
        routing_score:
          type: number
          format: float
        self_described: {}
    NodeDescription:
      type: object
      required:
      - moniker
      - website
      - security_contact
      - details
      properties:
        details:
          type: string
          description: details define other optional details.
        moniker:
          type: string
          description: moniker defines a human-readable name for the node.
        security_contact:
          type: string
          description: security contact defines an optional email for security contact.
        website:
          type: string
          description: website defines an optional website link.
    PagedResult_Gateway:
      type: object
      required:
      - page
      - size
      - total
      - items
      properties:
        items:
          type: array
          items:
            type: object
            required:
            - gateway_identity_key
            - bonded
            - performance
            - description
            - last_updated_utc
            - routing_score
            - config_score
            properties:
              bonded:
                type: boolean
              bridges: {}
              config_score:
                type: integer
                format: int32
                minimum: 0
              description:
                $ref: '#/components/schemas/NodeDescription'
              explorer_pretty_bond: {}
              gateway_identity_key:
                type: string
              last_ports_check_utc:
                type:
                - string
                - 'null'
              last_probe_log:
                type:
                - string
                - 'null'
              last_probe_result: {}
              last_testrun_utc:
                type:
                - string
                - 'null'
              last_updated_utc:
                type: string
              performance:
                type: integer
                format: int32
                minimum: 0
              ports_check: {}
              routing_score:
                type: number
                format: float
              self_described: {}
        page:
          type: integer
          minimum: 0
        size:
          type: integer
          minimum: 0
        total:
          type: integer
          minimum: 0
